In [2]:
import pandas as pd
import os
import requests
import json
import matplotlib.pyplot as plt

In [3]:
weather_df = pd.read_csv("../final-resources/EPL_scores_attendances.csv")
weather_df.head()
#weather_df["Date"] = weather_df["Date"].astype('datetime64[D]')
#weather_df["Date"] = weather_df["Date"].dt.strftime("20%y/%d/%m")
weather_df

,Div,Date,Time,HomeTeam,AwayTeam,HomeScore,AwayScore,Result,HomeTeam ID,AwayTeam ID,City,Team ID,Opponent,Attendance
0,E0,2019-08-09,20:00,Liverpool,Norwich,4,1,H,EPL9,EPL13,Liverpool,EPL9,Norwich City,53333.0
1,E0,2019-08-10,12:30,West Ham,Man City,0,5,A,EPL18,EPL10,London,EPL18,Manchester City,59870.0
2,E0,2019-08-10,15:00,Watford,Brighton,0,3,A,EPL17,EPL3,Watford,EPL17,Brighton & Hove Albion,20245.0
3,E0,2019-08-10,17:30,Tottenham,Aston Villa,3,1,H,EPL16,EPL1,London,EPL16,Aston Villa,60407.0
4,E0,2019-08-10,15:00,Crystal Palace,Everton,0,0,D,EPL6,EPL7,London,EPL6,Everton,25151.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,E0,2020-07-12,14:15,Aston Villa,Crystal Palace,2,0,H,EPL1,EPL6,Birmingham,EPL1,Crystal Palace,NaN
347,E0,2020-07-12,12:00,Wolves,Everton,3,0,H,EPL19,EPL7,Wolverhampton,EPL19,Everton,NaN
348,E0,2020-07-12,19:00,Bournemouth,Leicester,4,1,H,EPL2,EPL8,Bournemouth,EPL2,Leicester City,NaN
349,E0,2020-07-12,16:30,Tottenham,Arsenal,2,1,H,EPL16,EPL0,London,EPL16,Arsenal,NaN
350,E0,2020-07-13,20:00,Man United,Southampton,2,2,D,EPL11,EPL15,Manchester,EPL11,Southampton,NaN

In [4]:
cities = []
cities = weather_df[" City"]
lat = []
lng = []

In [5]:
query = "https://maps.googleapis.com/maps/api/geocode/json"
from config import gkey
# Exception Handling
#address = str(lat) + "," + str(lng)
for row in cities:
        try:
                params = {"address": str(row)+","+"England", "key": gkey}
                response = requests.get(query,params=params).json()
                lat.append(response["results"][0]["geometry"]["location"]["lat"])
                lng.append(response["results"][0]["geometry"]["location"]["lng"])
               
                # Increase Processing Record Counter by 1 For Each Loop

        except: 
                print("Oops")

In [6]:
weather_df["Latitude"] = lat
weather_df["Longitude"] = lng 
weather_df

,Div,Date,Time,HomeTeam,AwayTeam,HomeScore,AwayScore,Result,HomeTeam ID,AwayTeam ID,City,Team ID,Opponent,Attendance,Latitude,Longitude
0,E0,2019-08-09,20:00,Liverpool,Norwich,4,1,H,EPL9,EPL13,Liverpool,EPL9,Norwich City,53333.0,53.408371,-2.991573
1,E0,2019-08-10,12:30,West Ham,Man City,0,5,A,EPL18,EPL10,London,EPL18,Manchester City,59870.0,51.507351,-0.127758
2,E0,2019-08-10,15:00,Watford,Brighton,0,3,A,EPL17,EPL3,Watford,EPL17,Brighton & Hove Albion,20245.0,51.656489,-0.390320
3,E0,2019-08-10,17:30,Tottenham,Aston Villa,3,1,H,EPL16,EPL1,London,EPL16,Aston Villa,60407.0,51.507351,-0.127758
4,E0,2019-08-10,15:00,Crystal Palace,Everton,0,0,D,EPL6,EPL7,London,EPL6,Everton,25151.0,51.507351,-0.127758
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,E0,2020-07-12,14:15,Aston Villa,Crystal Palace,2,0,H,EPL1,EPL6,Birmingham,EPL1,Crystal Palace,NaN,52.486243,-1.890401
347,E0,2020-07-12,12:00,Wolves,Everton,3,0,H,EPL19,EPL7,Wolverhampton,EPL19,Everton,NaN,52.586973,-2.128820
348,E0,2020-07-12,19:00,Bournemouth,Leicester,4,1,H,EPL2,EPL8,Bournemouth,EPL2,Leicester City,NaN,50.719164,-1.880769
349,E0,2020-07-12,16:30,Tottenham,Arsenal,2,1,H,EPL16,EPL0,London,EPL16,Arsenal,NaN,51.507351,-0.127758
350,E0,2020-07-13,20:00,Man United,Southampton,2,2,D,EPL11,EPL15,Manchester,EPL11,Southampton,NaN,53.480759,-2.242631

In [ ]:
lat = weather_df["Latitude"]
lng = weather_df["Longitude"]
date = weather_df["Date"]
formatver = "json"
q = str(latitude1) + "," + str(longitude1)
averagetemp = []

In [7]:
url = "http://api.worldweatheronline.com/premium/v1/past-weather.ashx"
from config import weather_key1
key = weather_key1
averagetemp = []
formatver = "json"
for index,row in weather_df.iterrows():
    lat = row["Latitude"]
    lng = row["Longitude"]
    date = row["Date"]
    q = str(lat) + "," + str(lng)
    #try:
    params = {"q": q,"format": formatver,"key" : key,"date": date}
    response = requests.get(url,params=params).json()
    averagetemp.append(response["data"]["weather"][0]["avgtempF"])
  #  except: 
   #             print("Oops")

In [ ]:
print(averagetemp)

In [8]:
weather_df["Avg Temp (in F)"] = averagetemp
weather_df

,Div,Date,Time,HomeTeam,AwayTeam,HomeScore,AwayScore,Result,HomeTeam ID,AwayTeam ID,City,Team ID,Opponent,Attendance,Latitude,Longitude,Avg Temp (in F)
0,E0,2019-08-09,20:00,Liverpool,Norwich,4,1,H,EPL9,EPL13,Liverpool,EPL9,Norwich City,53333.0,53.408371,-2.991573,69
1,E0,2019-08-10,12:30,West Ham,Man City,0,5,A,EPL18,EPL10,London,EPL18,Manchester City,59870.0,51.507351,-0.127758,68
2,E0,2019-08-10,15:00,Watford,Brighton,0,3,A,EPL17,EPL3,Watford,EPL17,Brighton & Hove Albion,20245.0,51.656489,-0.390320,64
3,E0,2019-08-10,17:30,Tottenham,Aston Villa,3,1,H,EPL16,EPL1,London,EPL16,Aston Villa,60407.0,51.507351,-0.127758,68
4,E0,2019-08-10,15:00,Crystal Palace,Everton,0,0,D,EPL6,EPL7,London,EPL6,Everton,25151.0,51.507351,-0.127758,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,E0,2020-07-12,14:15,Aston Villa,Crystal Palace,2,0,H,EPL1,EPL6,Birmingham,EPL1,Crystal Palace,NaN,52.486243,-1.890401,64
347,E0,2020-07-12,12:00,Wolves,Everton,3,0,H,EPL19,EPL7,Wolverhampton,EPL19,Everton,NaN,52.586973,-2.128820,61
348,E0,2020-07-12,19:00,Bournemouth,Leicester,4,1,H,EPL2,EPL8,Bournemouth,EPL2,Leicester City,NaN,50.719164,-1.880769,63
349,E0,2020-07-12,16:30,Tottenham,Arsenal,2,1,H,EPL16,EPL0,London,EPL16,Arsenal,NaN,51.507351,-0.127758,73
350,E0,2020-07-13,20:00,Man United,Southampton,2,2,D,EPL11,EPL15,Manchester,EPL11,Southampton,NaN,53.480759,-2.242631,62

In [9]:
weather_df.to_csv("../final-resources/EPL_scores_att_weather.csv")